#!/bin/bash

echo "=== Common Dockerfile Issues to Fix ==="
echo ""
echo "Issues found:"
echo "1. Duplicate postgresql-client packages (lines 24 and 177-178)"
echo "2. Mixing 'apt' and 'apt-get' commands"
echo "3. Not cleaning apt cache consistently"
echo "4. Missing && between some commands"
echo ""
echo "Potential build failures:"
echo "- Network timeouts downloading packages"
echo "- GPG key errors for repositories"
echo "- Package conflicts"
echo "- Out of disk space"
echo "- Missing dependencies"
echo ""
echo "Quick fixes to try:"
echo ""
echo "1. Clean Docker cache:"
echo "   docker system prune -a --volumes"
echo ""
echo "2. Increase Docker Desktop resources:"
echo "   - Memory: 8GB minimum (16GB recommended)"
echo "   - Disk: 50GB minimum"
echo ""
echo "3. Build with network retry:"
echo "   docker build --network=host --build-arg BUILDKIT_INLINE_CACHE=1 ."
echo ""
echo "4. Check Docker Desktop WSL2 integration:"
echo "   - Settings > Resources > WSL Integration"
echo "   - Ensure your distro is enabled"