services:
  babelfish:
    build: 
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      # Mount workspace
      - ..:/workspace:cached
      # Persist Babelfish data
      - babelfish-data:/var/lib/babelfish/data
      # Persist backup directory (Docker named volume)
      - babelfish-backups:/var/lib/babelfish/bbf_backups
      # Windows-accessible backup directory (host mount - from .env file)
      - ${BBF_HOST_BACKUP_PATH}:/var/lib/babelfish/windows_backups:rw
    environment:
      # PostgreSQL/Babelfish connection settings (from .env file)
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      # Container initialization settings (from .env file)
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_DATABASE=${ADMIN_DATABASE}
      - MIGRATION_MODE=${MIGRATION_MODE}
      # Babelfish TDS settings (from .env file)
      - BABELFISH_TDS_PORT=${BABELFISH_TDS_PORT}
      # Backup directory settings (from .env file)
      - BBF_DOCKER_BACKUPS=${BBF_DOCKER_BACKUPS}
      - BBF_WINDOWS_BACKUPS=${BBF_WINDOWS_BACKUPS}
      - BBF_HOST_BACKUP_PATH=${BBF_HOST_BACKUP_PATH}
      - TARGET_PGHOST=${TARGET_PGHOST}
      # Locale settings (from .env file)
      - LC_ALL=${LC_ALL}
      - LANG=${LANG}
      - LANGUAGE=${LANGUAGE}
    ports:
      # Map container ports to host ports to avoid conflicts
      - "3341:1433"  # Babelfish TDS (SQL Server protocol) - host:container
      - "2345:5432"  # PostgreSQL native - host:container
      - "2223:22"    # SSH - host:container
    networks:
      - babelfish-network
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /start.sh

volumes:
  babelfish-data:
    driver: local
  babelfish-backups:
    driver: local

networks:
  babelfish-network:
    driver: bridge