services:
  babelfish:
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      # Mount workspace
      - ..:/workspace:cached
      # Persist Babelfish data
      - babelfish-data:/var/lib/babelfish/data
      # Persist backup directory (Docker named volume)
      - babelfish-backups:/var/lib/babelfish/bbf_backups
      # Windows-accessible backup directory (host mount)
      - /mnt/c/Users/rmosw/bbf_backups:/var/lib/babelfish/windows_backups:rw
    environment:
      # PostgreSQL/Babelfish connection settings
      - PGHOST=localhost
      - PGPORT=5432
      - PGDATABASE=babelfish_db
      - PGUSER=babelfish_admin
      - PGPASSWORD=secret_password
      # Babelfish TDS settings
      - BABELFISH_TDS_PORT=1433
      # Backup directory settings
      - BBF_DOCKER_BACKUPS=/var/lib/babelfish/bbf_backups
      - BBF_WINDOWS_BACKUPS=/var/lib/babelfish/windows_backups
      - BBF_HOST_BACKUP_PATH=/mnt/c/Users/rmosw/bbf_backups
      # Locale settings
      - LC_ALL=C
      - LANG=C
      - LANGUAGE=C
    ports:
      # Map container ports to host ports to avoid conflicts
      - "3341:1433"  # Babelfish TDS (SQL Server protocol) - host:container
      - "2345:5432"  # PostgreSQL native - host:container
      - "2223:22"    # SSH - host:container
    networks:
      - babelfish-network
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /start.sh

volumes:
  babelfish-data:
    driver: local
  babelfish-backups:
    driver: local

networks:
  babelfish-network:
    driver: bridge